Seo 181194 intall docs courage issues hotfix 25.1.35
syncfusion-content/install-docs pull request #509
Opened 2024-04-03 08:53 UTC by Faith-Atieno

Hi @gowthamanthavasiyappan 
Please review changes made
Regards,
Faith

2024-04-03 11:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-181194-Intall-Docs-Courage-issues-Hotfix-25.1.35](https://ci.syncfusion.com/job/Content/job/install-docs/18/console)**

2024-04-03 11:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-181194-Intall-Docs-Courage-issues-Hotfix-25.1.35](https://ci.syncfusion.com/job/Content/job/install-docs/18/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/18/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/18/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/18/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/18/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/18/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/18/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/18/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/18/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-04-03 13:27 UTC, gowthamanthavasiyappan requested changes
Commented

2024-04-03 13:27 UTC, gowthamanthavasiyappan commented on Common/Essential-Studio/Release-notes/v25.1.38.md
> +            {{ '[https://help.syncfusion.com/wpf/release-notes/v25.1.38?type=all](https://help.syncfusion.com/wpf/release-notes/v25.1.38?type=all)' | markdownify }}
Why you have changed the platform name?

2024-04-04 12:00 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-181194-Intall-Docs-Courage-issues-Hotfix-25.1.35](https://ci.syncfusion.com/job/Content/job/install-docs/19/console)**

2024-04-04 12:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-181194-Intall-Docs-Courage-issues-Hotfix-25.1.35](https://ci.syncfusion.com/job/Content/job/install-docs/19/console)**

2024-04-04 12:09 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-181194-Intall-Docs-Courage-issues-Hotfix-25.1.35](https://ci.syncfusion.com/job/Content/job/install-docs/19/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/19/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/19/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/19/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/19/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/19/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/19/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/19/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/install-docs/19/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-04-05 04:56 UTC, gowthamanthavasiyappan approved these changes
Approved

2024-04-05 06:54 UTC, Aishwarya-Ganesan approved these changes
fine

2024-04-05 06:54 UTC, merged